### ISSUE TITLE
Can we add `event.metaKey` here for supporting mac?

### ISSUE THREAD

**Issue by iskandarovBakshi** [samuhmatos/nextjs-progressloader#1]
https://github.com/samuhmatos/nextjs-progressloader/blob/7aeab2a6391b939991c9f9ded97207dfcada93d0/src/services/progressService.ts#L53-L56

**Comment by samuhmatos** [comment]
Hey, @iskandarovBakshi 

The Mac supporting added. I hope you enjoy the update😉
